CHANGES.md
openneuro/download.py
setup.cfg

Also adds special handling for certain files (TSV, JSON) that will
not be streamed and for which the server doesn't report a Content-Length.
For these files, the data is entirely contained within the response
body.

Don't rely on API-reported file size, but on HTTP response

---

openneuro/download.py

This is one solution to just add it to the text but, more broadly, the documentation could also be changed to include input types. That might help users avoid getting uninformative errors when, for instance, passing a string as an input to `on.download`.

[DOC] Clarified input type for input and output

---

openneuro/download.py
openneuro/tests/test_download.py

The retry-on-timeout logic is adding some code duplication again, but I'd like to schedule this for a later refactoring: IIRC, our HTTP library (httpx) will add native support for this. Question is, when 😅

Check if requested tag exists; if is doesn't, provide helpful error message

---

CHANGES.md
openneuro/download.py

This would try to download the entire content in some cases,
leading to a timeout.
Note that this will not resolve the concurrency issue we witnessed
at https://github.com/autoreject/autoreject/pull/209#issuecomment-842935106

Don't stream the HEAD response

---

.github/workflows/run-linter.yml
.github/workflows/run-tests.yml
CHANGES.md
openneuro/download.py
openneuro/tests/test_download.py
setup.cfg

- Ramp up timeouts from 5 to 30 seconds for downloads from `openneuro.org`.
- Drop support for Python 3.6. `openneuro-py` now requires Python 3.7 or newer.  This change makes development easier.
- Add problematic dataset as a test case.

Increase timeouts to up to 30 sec; drop Py 3.6

---

CHANGES.md
openneuro/download.py
setup.cfg

This allows for an easier check whether a file has been
completely downloaded.

Disable transfer encoding (i.e., compression)

---

CHANGES.md
openneuro/download.py
openneuro/openneuro.py

If neither the API nor the HTTP server provide the file size, don't download the file just for size determination. This won't allow us to display progress bars anymore in this case, but it will avoid downloading the same file twice. Unfortunately, resuming such downloads will be impossible, too: we'll simply re-download the files. Note that this only applies to files hosted on OpenNeuro.org for which we cannot determine the file size.
This PR also massively reduces memory footprint (by 2 orders of magnitude):
`main`:
this PR:
x-ref https://github.com/autoreject/autoreject/pull/209

Don't download  file(s) just to determine size

---

CHANGES.md
openneuro/download.py

Don't crash if the local `dataset_description.json` file is empty when trying to resume an aborted download.

Don't crash if local dataset_description.json is empty

---

CHANGES.md
openneuro/download.py

I just glanced at the errant filename for https://github.com/mne-tools/mne-bids-pipeline/pull/600, it only became glaringly obvious what the error was once I offered some suggestions:
```
RuntimeError: Could not find path in the dataset:
- sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-01_events.tsvsub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-01_eeg.set
Perhaps you mean one of these paths:
- sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-01_events.tsv
- sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-14_events.tsv
- sub-001/eeg/sub-001_task-AudioCueWalkingStudy_run-13_events.tsv
Please check your includes.
```
This PR makes these suggestions.

ENH: Suggest fixes

---

openneuro/download.py

Locally I get something that seems to work:
```
$ python -ui mne_bids_pipeline/tests/run_tests.py --download=1 ds000248
...
🌍 Preparing to download ds000248 …
📁 Traversing directory structure for ds000248 (this can take a while) …
derivatives 
│ derivatives/freesurfer 
│ │ derivatives/freesurfer/subjects 
│ │ │ derivatives/freesurfer/subjects/fsaverage 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/bem 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/label 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/mri 
│ │ │ │ │ derivatives/freesurfer/subjects/fsaverage/mri/transforms 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/mri.2mm 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/scripts 
│ │ │ │ derivatives/freesurfer/subjects/fsaverage/surf 
│ │ │ │ …
```

MAINT: Update for latest API

---

openneuro/download.py

I *think* this will help with this error:
https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3500/workflows/ef59c338-ff37-4295-a0c5-b2bb17c7bf32/jobs/40716
```
File "/home/circleci/python_env/lib/python3.10/site-packages/openneuro/download.py", line 206, in _get_download_metadata
raise RuntimeError(f'Query failed: '
RuntimeError: Query failed: "502 Server Error: Bad Gateway for url: https://openneuro.org/crn/graphql"
```
Because the error code is 502 (bad gateway), not 504 (gateway timeout), I think it's maybe not being caught properly?

ENH: Better error code check

---

CHANGES.md
README.md
openneuro/__init__.py
openneuro/_download.py
openneuro/config.py
openneuro/download.py
openneuro/openneuro.py
openneuro/tests/test_config.py
openneuro/tests/test_download.py
pyproject.toml

To download restricted datasets, we need to authenticate ourselves using an API token. This PR adds a new command `openneuro login` to write the API token to the `~/.openneuro` config file. The `openneuro-py download` command has been modified to send the token along as a cookie.
fixes #60

Add openneuro-py login command to enable authentication

---

.github/workflows/run-tests.yml
pyproject.toml

Switch build backend to hatchling

---

CHANGES.md
src/openneuro/_download.py

This adds a user-agent to both the requests session used for GraphQL queries and the httpx client used for file downloading.
Closes #123.

Send User-Agent header

---

src/openneuro/_download.py

Since https://github.com/tqdm/tqdm/issues/1213 has been merged, I think this special case can be removed (as per the comment).

Remove VS Code special casing

---

.pre-commit-config.yaml
README.md
pyproject.toml
src/openneuro/_cli.py
src/openneuro/tests/test_download.py

Omit printing some default values on the help screen.

Don't display default parameter values for some parameters where showing them doesn't make much sense because they're `None`

---

pyproject.toml

In 0.12.1, Typer was significantly reorganized.
- `typer-slim` is the library (for `import typer`)
- `typer-slim[standard]` adds optional dependencies (currently `rich` and `shellingham`, basically equivalent to the old `typer[all]`)
- `typer-cli` is the `typer` command-line tool
- `typer` is now basically a metapackage that brings in *all of the above*, and it no longer has an `all` extra
Pip will warn about this and proceed,
```
WARNING: typer 0.12.1 does not provide the extra 'all'
```
but there are other tools that will fail hard when asked to resolve a (now) nonexistent extra.
Since this project doesn’t need the `typer` command-line tool, it looks like changing the dependency to `typer-slim[standard]` is the best way forward.
See https://typer.tiangolo.com/release-notes/#0121 and …

Change the `typer[all]` dependency to `typer-slim[standard]`

---

.github/workflows/python-publish.yml

Just to be sure we can always derive the correct version number dynamically.
x-ref #160
cc @cbrnr @larsoner

In the "publish" workflow, check out with `fetch-depth=0`

---

.git_archival.txt

Remove `ref-names` from git archival settings

---

.gitignore
src/openneuro/_download.py

I always forget how to submit bug reports to OpenNeuro. So to save myself some effort next time, turn this error message:
E   RuntimeError: Error 404 when trying to download /home/larsoner/mne_data/ds000248/derivatives/freesurfer/subjects/fsaverage/label/Yeo_Brainmap_fsaverage_README from https://s3.amazonaws.com/openneuro.org/ds000248/derivatives/freesurfer/subjects/fsaverage/label/Yeo_Brainmap_fsaverage_README?versionId=WuMze1X4S_cLoRCbEs5IpCIOJMe2VT41
Into this:
RuntimeError: Error 404 when trying to download /home/larsoner/mne_data/ds000248/derivatives/freesurfer/subjects/fsaverage/label/lh.BA1_exvivo.label. If this is unexpected:
E   
E   1. Navigate to https://openneuro.org/crn/graphql
E   2. Enter and run the operation: query { snapshot(datasetId: "ds000248" , tag: "1.2.4" ) { id …

ENH: More verbose error message
